### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by ris58h** [XavierDuthil/youtube-compilation-helper#1]
I believe it is possible to adapt it for Firefox.
First of all I've tried to use in Firefox but it seems that it just doesn't detect any tracklist.

Second: after loading it in Firefox I've got `Reading manifest: Error processing permissions.2: Value "background" ` message.  Is it possible to get rid of "background" permission?

**Comment by XavierDuthil** [comment]
Hi @ris58h, thank you for reaching out.

Firefox version [is now out](https://addons.mozilla.org/en-US/firefox/addon/youtube-tracklist-control/), and from now on will be built from the [firefox_version](XavierDuthil/youtube-tracklist-control/firefox_version) branch.

There were indeed some small changes to make to the manifest.json, and some behaviour changes (good practices actually) to satisfy the linter, but overall the transition went pretty well.

Thanks for your involvement!
