### ISSUE TITLE
Feature request: push notification on track change

### ISSUE THREAD

**Issue by blakewatson** [XavierDuthil/youtube-compilation-helper#3]
A push notification that shows the current track title/artist. Could be an optional setting. This would be cool for when you’re listening to music and the browser isn’t in focus.

**Comment by XavierDuthil** [comment]
@blakewatson Sorry it took some time, but you will find a toggleable button for enabling Push notifications in the next release of this extension. Thank you for your interest !
![image](https://user-images.githubusercontent.com/31845024/156897270-0446c014-1a8b-483c-a23f-9a5418ad4cea.png)

**Comment by blakewatson** [comment]
Thanks for the new feature @XavierDuthil!
