### ISSUE TITLE
Bug: can't see any details on the menu! 

### ISSUE THREAD

**Issue by Droyk** [XavierDuthil/youtube-compilation-helper#4]
![image](https://user-images.githubusercontent.com/15848350/156877495-7cc930e6-014f-4e97-b7e4-135b6ae03e59.png)

Microsoft Edge
Version 98.0.1108.62 (Official build) (64-bit)
Please fix it if you can!

**Comment by XavierDuthil** [comment]
Hello @Droyk, thank you for reaching out.

Respectfully, I think you misunderstood the purpose of this extension. It only extracts a tracklist concerning a single YouTube video (like albums or compilations).

It needs a description or comment containing the track timestamps (the video you showed doesn't contain any), like in this example:
![image](https://user-images.githubusercontent.com/31845024/156881687-e7243341-8955-4960-8b29-9fd30714b2b3.png)

I'm sure there exist other extensions for controlling a YouTube playlist (the queue we can see on your screenshot), if this is what you want :)

**Comment by XavierDuthil** [comment]
My bad, I thought that you only mentionned the tracklist, but I see now that the YouTube video name doesn't appear either in the popup as it should.

I will address a fix immediately.

**Comment by XavierDuthil** [comment]
@Droyk The updated extension has been submitted to the Chrome extensions store (Firefox is coming), so it should be available shortly. The update will also contain a new Push Notifications feature (toggleable) as requested in https://github.com/XavierDuthil/youtube-tracklist-control/issues/3.

**Comment by Droyk** [comment]
can you please update the release page with changelogs? it helps in tracking the release progress.

**Comment by XavierDuthil** [comment]
@Droyk Alright done: https://github.com/XavierDuthil/youtube-tracklist-control/releases/tag/2.7.0

I included the full changelog in this one, as it's the first release I publish. Following releases will contain only the recent changes.
